name: Deploy themes to GitHub Pages
on:
  push:
    branches:
      - main
      - pycontw2025-theme-1-info-first
      - pycontw2025-theme-2-editorial-cozy
      - pycontw2025-theme-3-minimal-monochrome
      - pycontw2025-theme-4-playful-pastel-tech
      - pycontw2025-theme-5-warm-civic-sans
  workflow_dispatch:

permissions:
  contents: write  # needed for the deploy action to push commits

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - branch: main
            slug: ""           # deploy to root
          - branch: pycontw2025-theme-1-info-first
            slug: theme-1
          - branch: pycontw2025-theme-2-editorial-cozy
            slug: theme-2
          - branch: pycontw2025-theme-3-minimal-monochrome
            slug: theme-3
          - branch: pycontw2025-theme-4-playful-pastel-tech
            slug: theme-4
          - branch: pycontw2025-theme-5-warm-civic-sans
            slug: theme-5
    concurrency: pages-${{ matrix.branch }}
    steps:
      - name: Check if should run
        id: should_run
        run: |
          if [ "${{ github.ref_name }}" == "${{ matrix.branch }}" ]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi
          
      - uses: actions/checkout@v4
        if: steps.should_run.outputs.should_run == 'true'
        with:
          ref: ${{ matrix.branch }}

      - uses: actions/setup-node@v4
        if: steps.should_run.outputs.should_run == 'true'
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci
        if: steps.should_run.outputs.should_run == 'true'

      # Build with the right base for subfolders
      - name: Build (subfolder)
        if: steps.should_run.outputs.should_run == 'true' && matrix.slug != ''
        run: npm run build -- --base=/${{ matrix.slug }}/

      - name: Build (root)
        if: steps.should_run.outputs.should_run == 'true' && matrix.slug == ''
        run: |
          npm run build
          # Add one-time files at the root site
          echo "pycontw2025.scc.tw" > dist/CNAME
          touch dist/.nojekyll
          # Copy theme switcher page
          cp theme-switcher.html dist/themes.html

      # Deploy to gh-pages; 'target-folder' publishes under /theme-x/
      - name: Deploy (subfolder)
        if: steps.should_run.outputs.should_run == 'true' && matrix.slug != ''
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          target-folder: ${{ matrix.slug }}
          clean: false  # keep other /theme-* folders

      - name: Deploy (root)
        if: steps.should_run.outputs.should_run == 'true' && matrix.slug == ''
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean: false